asf_website_public_homepage:
    path: /
    defaults: { _controller: "ASFWebsiteBundle:Public:index" }
     
asf_website_public_page_route:
    path: /{path}
    defaults: { _controller: "ASFWebsiteBundle:Public:page" }
    requirements:
        path: "^(?!admin|login|blog|js|css|fonts).+"