# Backend
asf_website_backend:
    prefix: /admin
    resource: "@ASFWebsiteBundle/Resources/config/routing/backend.yml"
       
# Frontend
asf_website_frontend:
    resource: "@ASFWebsiteBundle/Resources/config/routing/frontend.yml"