asf_website_config_list:
    path: /list
    defaults: { _controller: "ASFWebsiteBundle:WebsiteConfig:list" }
    
asf_website_config_edit:
    path: /edit/{id}
    defaults: { _controller: "ASFWebsiteBundle:WebsiteConfig:edit" }
    
asf_website_config_add:
    path: /add
    defaults: { _controller: "ASFWebsiteBundle:WebsiteConfig:edit" }
    
asf_website_config_delete:
    path: /delete/{id}
    defaults: { _controller: "ASFWebsiteBundle:WebsiteConfig:delete" }